version: '3.4'

services:
  app:
    container_name: cure51.app
    image: cure51/app
    build: 
      context: ./app
#    command: >
#      sh -c "yarn && yarn dev"
    volumes:
      - ./app:/app
    ports:
      - 5002:3000
    networks:
      - mysql
    environment:
      - NEXT_PUBLIC_WORDPRESS_API_URL=${NEXT_PUBLIC_WORDPRESS_API_URL}

networks:
  mysql:
    name: mysql
    external: true
