version: '3.4'

services:
  wordpress:
    container_name: cure51.wordpress
    image: wordpress:latest
    ports:
      - 8004:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: '${DB_NAME}'
      WORDPRESS_DB_USER: '${DB_USER}'
      WORDPRESS_DB_PASSWORD: '${DB_ROOT_PASSWORD}'
    volumes:
      - ./wp-plugins:/var/www/html/wp-content/plugins/
      - ./wp-uploads:/var/www/html/wp-content/uploads/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - mysql

networks:
  mysql:
    name: mysql
    external: true
